title: Golam Muktadir Curriculum Vitae
description:  Golam Muktadir's details Curriculum Vitae
url: https://gmuktadir.github.io/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
